# LevelingCore configuration
#
# =========================
# Database Configuration
# =========================
#
# Supported JDBC URLs:
#   H2 (file):
#     jdbc:h2:file:./data/plugins/levelingcore/levelingcore;MODE=PostgreSQL
#
#   MySQL:
#     jdbc:mysql://host:port/dbname
#     jdbc:mysql://host:port/dbname?user=dbuser&password=dbpass
#
#   MariaDB:
#     jdbc:mariadb://host:port/dbname
#     jdbc:mariadb://host:port/dbname?user=dbuser&password=dbpass
#
#   PostgreSQL:
#     jdbc:postgresql://host:port/dbname
#     jdbc:postgresql://host:port/dbname?user=dbuser&password=dbpass
#
# Notes:
# - H2 commonly uses empty username/password unless you configured otherwise.
# - For MySQL/MariaDB/Postgres, set username/password.
#
database:
  jdbcUrl: "jdbc:h2:file:./data/plugins/levelingcore/levelingcore;MODE=PostgreSQL"
  username: ""
  password: ""
  maxPoolSize: 10

# =========================
# Leveling Formula
# =========================
#
# Supported types:
#   - EXPONENTIAL: XP floor at level L is baseXp * (L - 1) ^ exponent
#   - LINEAR:      XP floor at level L is xpPerLevel * (L - 1)
#   - TABLE:       XP floor at level L is defined in a CSV file
#   - CUSTOM:      XP floor at level L is defined by a math expression
#
# Notes:
# - XP migration is enabled by default. Set migrateXP to false to disable.
# - Changing the formula will recompute XP to preserve player levels.
#
formula:
  type: "EXPONENTIAL"
  migrateXP: true
  exponential:
    baseXp: 100.0
    exponent: 1.7
    # Maximum level supported by this formula
    maxLevel: 100000
  linear:
    xpPerLevel: 100
    # Maximum level supported by this formula
    maxLevel: 100000
  table:
    # CSV file relative to the data directory
    file: "levels.csv"
  custom:
    # Expression returns the XP floor for a level.
    #
    # Available variables:
    #   - level      (current level, integer >= 1)
    #
    # You may also reference any constants defined below.
    #
    # Example:
    #   exp(a * (level - 1)) * b / c
    #
    xpForLevel: "exp(a * (level - 1)) * b / c"

    # Optional constants referenced in the expression
    constants:
      a: 0.12
      b: 100
      c: 1

    # Maximum level supported by this formula (used for binary search)
    maxLevel: 100000
